config/routes.rb
Rails.application.routes.draw do
  resources :alarms
  root :to => "alarms#index"
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  scope :ordered, -> { order(created_at: :desc) }

  validate :description_must_be_upper_case

  def description=(value)
    self[:description]= value&.upcase
  end

  def description_must_be_upper_case
    errors.add(:base, 'description must be upper case') if description.upcase != description
  end

  def epoch_seconds
    Time.zone.now.to_i - created_at.to_i
  end

  def score
    order = Math.log10([vote_counter.to_f, 1].max) * 10
    (order + epoch_seconds).round(7)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.ordered

    @alarms = @alarms.sort { |x,y| y.score <=> x.score }
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    builder = Alarms::Create.new(params.require(:alarm).permit(:description))
    @alarm = builder.perform

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    Alarms::Update.new(@alarm, alarm_params).perform

    respond_to do |format|
      if @alarm.valid?
        format.html { redirect_to alarms_path, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:description, :up)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :vote_counter %>
    <%= form.number_field :vote_counter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Vote counter</th>
      <th>Vote</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.description %></td>
        <td><%= alarm.vote_counter %></td>
        <td><%= link_to "Vote", alarm_path(alarm.id, alarm: { up: true }), method: :put %></td>
        <td><%= alarm.score %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @alarm.description %>
</p>

<p>
  <strong>Vote counter:</strong>
  <%= @alarm.vote_counter %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BellBird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>